-- Demo jobs to ensure the platform always has representative data
-- These will be supplemented by real scraped data
INSERT INTO jobs (title, company, location, url, source, date_scraped, date_posted, job_type, workplace_type, department, salary_text, salary_min, salary_max, salary_currency, description_snippet, full_description, skills, dedup_key, is_active) VALUES
('Senior Java Developer', 'Wise', 'Tallinn', 'https://wise.com/careers', 'demo', CURRENT_DATE, CURRENT_DATE, 'FULL_TIME', 'HYBRID', 'Engineering', '4500-7000 EUR/month', 4500, 7000, 'EUR', 'Join our engineering team to build the future of international money transfers.', 'We are looking for a Senior Java Developer to join our Transfer Engineering team in Tallinn. You will work on high-throughput payment processing systems serving millions of customers worldwide.\n\nRequirements:\n- 5+ years of Java experience\n- Experience with Spring Boot and microservices\n- Strong knowledge of SQL and PostgreSQL\n- Experience with Kafka or similar messaging systems\n- Good understanding of CI/CD practices\n\nWhat we offer:\n- Competitive salary with stock options\n- Hybrid work model\n- Health insurance\n- Learning budget', '["Java", "Spring", "PostgreSQL", "Kafka", "Docker", "CI/CD"]', 'wise|senior java developer|tallinn', true),

('Frontend React Developer', 'Bolt', 'Tallinn', 'https://bolt.eu/careers', 'demo', CURRENT_DATE, CURRENT_DATE, 'FULL_TIME', 'HYBRID', 'Engineering', '3500-5500 EUR/month', 3500, 5500, 'EUR', 'Build the next generation of ride-hailing and delivery UI.', 'Bolt is looking for a talented Frontend Developer to join our team in Tallinn. You will work on consumer-facing applications used by millions of people across Europe and Africa.\n\nWhat you will do:\n- Build and maintain React applications\n- Work closely with designers and backend engineers\n- Optimize performance and user experience\n- Write tests and maintain code quality\n\nRequirements:\n- 3+ years of React experience\n- TypeScript proficiency\n- Experience with state management (Redux, MobX)\n- Understanding of web performance optimization\n- Experience with testing (Jest, Cypress)', '["React", "TypeScript", "JavaScript", "Node.js", "Git", "CI/CD"]', 'bolt|frontend react developer|tallinn', true),

('DevOps Engineer', 'Playtech', 'Tartu', 'https://playtech.com/careers', 'demo', CURRENT_DATE, CURRENT_DATE, 'FULL_TIME', 'ONSITE', 'Infrastructure', '4000-6000 EUR/month', 4000, 6000, 'EUR', 'Manage cloud infrastructure for one of Europe''s largest gaming platforms.', 'We are seeking a DevOps Engineer to help us scale our infrastructure. Playtech operates one of the world''s largest online gaming platforms.\n\nResponsibilities:\n- Design and maintain CI/CD pipelines\n- Manage AWS/GCP cloud infrastructure\n- Implement infrastructure as code with Terraform\n- Monitor and optimize system performance\n- Ensure high availability and disaster recovery\n\nRequirements:\n- 3+ years DevOps/SRE experience\n- Strong Linux administration skills\n- Experience with Docker and Kubernetes\n- Terraform or similar IaC tools\n- AWS or GCP certification preferred', '["Docker", "Kubernetes", "AWS", "Terraform", "Linux", "CI/CD", "Python"]', 'playtech|devops engineer|tartu', true),

('Python Data Engineer', 'Veriff', 'Tallinn', 'https://veriff.com/careers', 'demo', CURRENT_DATE, CURRENT_DATE, 'FULL_TIME', 'REMOTE', 'Data', '4000-6500 EUR/month', 4000, 6500, 'EUR', 'Build data pipelines powering identity verification AI.', 'Veriff is looking for a Data Engineer to join our Data Platform team. You will build and maintain the data infrastructure that powers our AI-based identity verification.\n\nWhat you will do:\n- Design and implement data pipelines using Python and Spark\n- Work with large-scale data processing systems\n- Build real-time data streaming solutions\n- Optimize data warehouse performance\n\nRequirements:\n- 3+ years of data engineering experience\n- Strong Python skills\n- Experience with Apache Spark, Airflow, or Kafka\n- SQL expertise (PostgreSQL, BigQuery)\n- Experience with cloud platforms (AWS/GCP)', '["Python", "SQL", "PostgreSQL", "AWS", "Docker", "Kafka", "Git"]', 'veriff|python data engineer|tallinn', true),

('Full-Stack TypeScript Developer', 'Pipedrive', 'Tallinn', 'https://pipedrive.com/careers', 'demo', CURRENT_DATE, CURRENT_DATE, 'FULL_TIME', 'HYBRID', 'Engineering', '3800-5800 EUR/month', 3800, 5800, 'EUR', 'Build CRM features used by 100,000+ companies worldwide.', 'Join Pipedrive, the #1 user-rated CRM, and help us build tools that sales teams love.\n\nRole:\n- Develop full-stack features with React and Node.js\n- Write clean, maintainable TypeScript code\n- Participate in code reviews and architecture discussions\n- Collaborate with product managers and designers\n\nRequirements:\n- 3+ years full-stack development experience\n- Strong TypeScript/JavaScript skills\n- React and Node.js experience\n- PostgreSQL or similar RDBMS\n- Experience with REST APIs and GraphQL', '["TypeScript", "React", "Node.js", "PostgreSQL", "GraphQL", "Docker", "Git"]', 'pipedrive|full-stack typescript developer|tallinn', true),

('iOS Developer', 'Starship Technologies', 'Tallinn', 'https://starship.xyz/careers', 'demo', CURRENT_DATE, CURRENT_DATE, 'FULL_TIME', 'HYBRID', 'Mobile', '3500-5500 EUR/month', 3500, 5500, 'EUR', 'Build the mobile app for autonomous delivery robots.', 'Starship Technologies is revolutionizing local delivery with autonomous robots. Join our mobile team to build the iOS app that customers use to order deliveries.\n\nWhat you will do:\n- Develop and maintain our iOS application in Swift\n- Implement new features and improve UX\n- Work with real-time location data and maps\n- Integrate with our robot fleet management system\n\nRequirements:\n- 3+ years iOS development with Swift\n- Experience with UIKit and SwiftUI\n- Knowledge of MapKit and CoreLocation\n- Experience with RESTful APIs\n- Understanding of CI/CD for mobile apps', '["Swift"]', 'starship technologies|ios developer|tallinn', true),

('QA Automation Engineer', 'Swedbank', 'Tallinn', 'https://swedbank.com/careers', 'demo', CURRENT_DATE, CURRENT_DATE, 'FULL_TIME', 'HYBRID', 'Quality', '3000-4500 EUR/month', 3000, 4500, 'EUR', 'Ensure quality of banking systems serving millions of customers.', 'Swedbank is looking for a QA Automation Engineer to join our digital banking team in Tallinn.\n\nResponsibilities:\n- Design and implement automated test frameworks\n- Write and maintain automated tests (UI, API, performance)\n- Participate in sprint planning and refinement\n- Collaborate with developers to ensure quality standards\n\nRequirements:\n- 2+ years of test automation experience\n- Java or Python programming skills\n- Experience with Selenium, Playwright, or Cypress\n- API testing experience (REST, GraphQL)\n- Knowledge of CI/CD pipelines', '["Java", "Python", "SQL", "Git", "CI/CD"]', 'swedbank|qa automation engineer|tallinn', true),

('Cloud Architect', 'Telia', 'Tallinn', 'https://telia.ee/careers', 'demo', CURRENT_DATE, CURRENT_DATE, 'FULL_TIME', 'HYBRID', 'Infrastructure', '5500-8000 EUR/month', 5500, 8000, 'EUR', 'Design cloud solutions for the Nordics'' largest telecom.', 'Telia Estonia is looking for an experienced Cloud Architect to lead our cloud transformation journey.\n\nWhat you will do:\n- Design and implement cloud-native architectures\n- Lead migration of legacy systems to cloud\n- Establish cloud governance and best practices\n- Mentor development teams on cloud patterns\n\nRequirements:\n- 7+ years of software engineering experience\n- 3+ years of cloud architecture (AWS/Azure/GCP)\n- Kubernetes and containerization expertise\n- Experience with microservices architecture\n- Cloud certification (AWS SA, Azure Architect) preferred', '["AWS", "Azure", "Kubernetes", "Docker", "Terraform", "Python", "Linux"]', 'telia|cloud architect|tallinn', true),

('Junior Python Developer', 'Helmes', 'Tallinn', 'https://helmes.com/careers', 'demo', CURRENT_DATE, CURRENT_DATE, 'FULL_TIME', 'ONSITE', 'Engineering', '1800-2800 EUR/month', 1800, 2800, 'EUR', 'Start your career at one of Estonia''s leading software companies.', 'Helmes is looking for a Junior Python Developer to join our growing team. Great opportunity for someone starting their career in software development.\n\nWhat you will do:\n- Develop web applications using Python/Django\n- Write unit and integration tests\n- Learn from experienced senior developers\n- Participate in agile development processes\n\nRequirements:\n- Basic Python programming knowledge\n- Understanding of SQL basics\n- Familiarity with Git\n- Interest in web development\n- BSc in Computer Science or equivalent experience\n\nWe offer:\n- Mentorship program\n- Learning budget\n- Flexible working hours', '["Python", "SQL", "Git"]', 'helmes|junior python developer|tallinn', true),

('Küberturbe spetsialist', 'Cybernetica', 'Tallinn', 'https://cyber.ee/careers', 'demo', CURRENT_DATE, CURRENT_DATE, 'FULL_TIME', 'ONSITE', 'Security', '4000-6000 EUR/kuus', 4000, 6000, 'EUR', 'Kaitse Eesti digitaalset infrastruktuuri.', 'Cybernetica otsib küberturbe spetsialisti, kes aitab kaitsta Eesti e-riigi infrastruktuuri.\n\nTöö kirjeldus:\n- Turvaauditite läbiviimine\n- Turvanõrkuste analüüs ja kõrvaldamine\n- Turvameetmete kavandamine ja rakendamine\n- Meeskonna koolitamine turvaküsimustes\n\nNõuded:\n- 3+ aastat küberturbe kogemust\n- Linux ja võrgu administratsiooni oskused\n- Kogemus SIEM süsteemidega\n- Sertifikaat (CISSP, CEH) on eeliseks\n- Eesti ja inglise keel\n\nPakume:\n- Konkurentsivõimelist palka\n- Erialast arendusvõimalust\n- Kaasaegset töökeskkonda', '["Linux", "Python"]', 'cybernetica|küberturbe spetsialist|tallinn', true);
